services:

  # minio:
  #   image: minio/minio
  #   ports:
  #     - '9000:9000'
  #     - '9002:9001'
  #   environment:
  #     MINIO_ROOT_USER: ${MINIO_ROOT_USER}
  #     MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
  #   command: server --console-address ":9001" /data
  #   healthcheck:
  #     test: [ "CMD", "curl", "-f", "http://minio:9000/minio/health/live" ]
  #     interval: 2s
  #     timeout: 10s
  #     retries: 5
  #   volumes:
  #     - ./volumes/storage:/data:z

  # minio-createbucket:
  #   image: minio/mc
  #   # depends_on:
  #   #   minio:
  #   #     condition: service_healthy
  #   entrypoint: >
  #     /bin/sh -c "
  #     /usr/bin/mc alias set supa-minio https://s3.mateoleal.com ${MINIO_USER} ${MINIO_PASSWORD};
  #     /usr/bin/mc mb --ignore-existing supa-minio/supabase;
  #     exit 0;
  #     "

  storage:
    container_name: supabase-storage
    image: supabase/storage-api:v1.19.1
    depends_on:
      db:
        # Disable this if you are using an external Postgres database
        condition: service_healthy
      rest:
        condition: service_started
      imgproxy:
        condition: service_started
      # minio:
      #   condition: service_healthy
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:5000/status"
        ]
      timeout: 5s
      interval: 5s
      retries: 3
    restart: unless-stopped
    environment:
      ANON_KEY: ${ANON_KEY}
      SERVICE_KEY: ${SERVICE_ROLE_KEY}
      POSTGREST_URL: http://rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
      UPLOAD_FILE_SIZE_LIMIT: 3221225472 # 3GB
      UPLOAD_FILE_SIZE_LIMIT_STANDARD: 3221225472 # 3GB
      UPLOAD_SIGNED_URL_EXPIRATION_TIME: 120
      TUS_URL_PATH: /upload/resumable
      TUS_MAX_SIZE: 3600000
      STORAGE_BACKEND: s3
      GLOBAL_S3_BUCKET: supabase
      GLOBAL_S3_ENDPOINT: http://192.168.71.9:9000
      GLOBAL_S3_PROTOCOL: http
      GLOBAL_S3_FORCE_PATH_STYLE: true
      AWS_ACCESS_KEY_ID: ${MINIO_USER}
      AWS_SECRET_ACCESS_KEY: ${MINIO_PASSWORD}
      AWS_DEFAULT_REGION: southamerica-north-1
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: natillera
      # TODO: https://github.com/supabase/storage-api/issues/55
      REGION: southamerica-north-1
      ENABLE_IMAGE_TRANSFORMATION: "true"
      IMGPROXY_URL: http://imgproxy:5001
    volumes:
      - ./volumes/storage:/var/lib/storage:z

  imgproxy:
    container_name: supabase-imgproxy
    image: darthsim/imgproxy:v3.8.0
    healthcheck:
      test: [ "CMD", "imgproxy", "health" ]
      timeout: 5s
      interval: 5s
      retries: 3
    environment:
      IMGPROXY_BIND: ":5001"
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: ${IMGPROXY_ENABLE_WEBP_DETECTION}
